export const ApiConstants = {
	lookups: {
		getCountry: "/api/country/get",
		getValidators: "/api/validator/shortlist",
		getCheckers: "/api/checker/shortlist",
		getSuppliers: "/api/supplier/shortlist",
		invoiceexpgroups: "/api/entry/invoiceexpgroups",
		invoicepurchasegroups: "/api/entry/invoicepurchasegroups",
	},
	file: {
		upload: "/api/file/upload",
		download: "/api/file/download",
		view: "/api/file/view",
	},
	auth: {
		login: "/api/auth/login",
		employeelogin: "/api/auth/employeelogin",
		changepassword: "/api/auth/changepassword",
		refreshtoken: "/api/auth/refresh",
		sendemailverification: "/email/sendemailverification",
		forgotpassword: "/password/forgotpassword",
	},
	user: {
		activateuser: "/api/admin/activateuser",
		deactivateuser: "/api/admin/deactivateuser",
		getuser: "/api/auth/getuser",
		profile: "/api/auth/profile",
	},
	client: {
		getclient: "/api/client/getclient",
		list: "/api/client/list",
		register: "/api/client/register",
		getpaymentlink: "/api/client/getpaymentlink",
		update: "/api/client/update",
		vatexpirydate: "/api/client/vatexpirydate",
		updatebyadmin: "/api/client/updatebyadmin",
		dashboardsummary: "/api/client/dashboardsummary",
		clientmonthwisegraph: "/api/entry/clientmonthwisegraph",
		currentvatperiod: "/api/client/currentvatperiod",
	},
	admin: {
		list: "/api/admin/list",
		register: "​​/api/admin/register",
		approveuser: "/api/admin/approveuser",
		addpaymentlink: "/api/client/addpaymentlink",
		deletepaymentlink: "/api/client/deletepaymentlink",
		updatetradelicenseexpiry: "/api/admin/updatetradelicenseexpiry",
		updateclient: "/api/admin/updateclient",
		update: "/api/admin/update",
		updatebyadmin: "/api/admin/updatebyadmin",
		expirydatelist: "/api/admin/expirydatelist",
		tradelicenseexpirydate: "/api/admin/tradelicenseexpirydate",
		dashboardsummary: "/api/admin/dashboardsummary",
		admincheckerpendinglist: "/api/entry/admincheckerpendinglist",
		admincheckerrejectedlist: "/api/entry/admincheckerrejectedlist",
		adminvalidatorpendinglist: "/api/entry/adminvalidatorpendinglist",
		adminvalidatorchekedlist: "/api/entry/admincheckedlist",
		adminlastweeksgraph: "/api/entry/adminlastweeksgraph",
		adminvatpayablegraph: "/api/entry/adminvatpayablegraph",
		clientshortlistbyadmin: "/api/admin/clientshortlistbyadmin",
	},
	checker: {
		clientlist: "/api/checker/clientlist",
		list: "/api/checker/list",
		register: "​​/api/checker/register",
		updatebyadmin: "/api/checker/updatebyadmin",
		update: "/api/checker/update",
		dashboardsummary: "/api/checker/dashboardsummary",
		dashboardrecenttile: "/api/checker/dashboardrecenttile",
		checkerlastweeksgraph: "/api/entry/checkerlastweeksgraph",
		checkervatpayablegraph: "/api/entry/checkervatpayablegraph",
		clientshortlistbychecker: "/api/checker/clientshortlistbychecker",
	},
	validator: {
		checkerlist: "/api/validator/checkerslist",
		list: "/api/validator/list",
		register: "/api/validator/register",
		updatebyadmin: "/api/validator/updatebyadmin",
		update: "/api/validator/update",
		dashboardsummary: "/api/validator/dashboardsummary",
		dashboardrecenttile: "/api/validator/dashboardrecenttile",
		validatorlastweeksgraph: "/api/entry/validatorlastweeksgraph",
		validatorvatpayablegraph: "/api/entry/validatorvatpayablegraph",
		clientshortlistbyvalidator: "/api/validator/clientshortlistbyvalidator",
	},
	supplier: {
		list: "/api/supplier/list",
		topsixsupplierslist: "/api/supplier/topsixsupplierslist",
		addsupplier: "/api/supplier/create",
		getsupplier: "/api/supplier/get",
		update: "/api/supplier/update",
	},
	plans: {
		history: "/api/plan/get",
		newplan: "/api/plan/create",
	},
	entry: {
		create: "/api/entry/create",
		clientpendinglist: "/api/entry/clientpendinglist",
		clientrecentlist: "/api/entry/clientrecentlist",
		clientdeleteentry: "/api/entry/clientdeleteentry",
		clientrequestfordelete: "/api/entry/clientrequestfordelete",
		checkerpendinglist: "/api/entry/checkerpendinglist",
		checkerapprovedlist: "/api/entry/checkerapprovedlist",
		checkercheckedlist: "/api/entry/checkercheckedlist",
		checkernoentrylist: "/api/entry/checkernoentrylist",
		checkerrejectedlist: "/api/entry/checkerrejectedlist",
		validatorpendinglist: "/api/entry/validatorpendinglist",
		validatorcheckedlist: "/api/entry/validatorcheckedlist",
		validatorapprovedlist: "/api/entry/validatorapprovedlist",
		validatorrejectedlist: "/api/entry/validatorrejectedlist",
		validatordeleteentry: "/api/entry/validatordeleteentry",
		setvalidatorstatus: "/api/entry/setvalidatorstatus",
		setcheckerstatus: "/api/entry/setcheckerstatus",
		checkinvoicenumberexists: "/api/entry/checkinvoicenumberexists",
		clientapprovedlist: "/api/entry/clientapprovedlist",
		clientrejectedlist: "/api/entry/clientrejectedlist",
	},
	summary: {
		clientdaywisesummary: "/api/entry/clientdaywisesummary",
	},
	sales: {
		create: "/api/sale/create",
		getData: "/api/sale/get",
		clientsalesreport: "/api/sale/clientsalesreport",
	},
	expenditure: {
		create: "/api/expenditure/create",
		getData: "/api/expenditure/get",
		clientexpenditurereport: "/api/expenditure/clientexpenditurereport",
	},
	purchase: {
		create: "/api/purchase/create",
		getData: "/api/purchase/get",
		clientpurchasereport: "/api/purchase/clientpurchasesreport",
	},
	vatreports: {
		vatreportperiodsforclient: "/api/vatreport/vatreportperiodsforclient",
		vatreportperiodsforothers: "/api/vatreport/vatreportperiodsforothers",
		vatreportforvalidator: "/api/vatreport/vatreportforvalidator",
		vatreportforvalidatorbyid: "/api/vatreport/vatreportforvalidatorbyid",
		vatreportforclient: "/api/vatreport/vatreportforclient",
		vatreportforothers: "/api/vatreport/vatreportforothers",
		createvatreport: "/api/vatreport/createvatreport",
		updatevatreport: "/api/vatreport/updatevatreport",
	},
	message: {
		contacts: "/api/message/contacts",
		getmessages: "/api/message/get",
		getallmessages: "/api/message/getallmessages",
		sendmessage: "/api/message/send",
	},
};
